language: python
python:
  - "2.7"

# command to install dependencies
script: python tests/__init__.py
branches:
  only:
    - master

sudo: false

cache:
  - apt
  - pip
addons:
  apt:
    packages:
      - python-scipy
      - python-numpy
      - python-pyside
      - python-h5py
      - python-matplotlib
      - python-skimage
      - python-cryptography

virtualenv:
  system_site_packages: true

install:
  - pip install .

script:
  - pylint xicamlauncher xicam pipeline --errors-only
  - coverage run tests.py

after_success:
  - pip install codecov --upgrade  # add coverage integration service
  - codecov