language: python
python:
  - "2.7"

# command to install dependencies
script: python tests/__init__.py
branches:
  only:
    - master

sudo: false

cache: apt
addons:
  apt:
    packages:

install:
  - pip install .

script:
  - pylint xicamlauncher xicam pipeline --errors-only
  - coverage run tests.py

after_success:
  - pip install codecov --upgrade  # add coverage integration service
  - codecov