language: python
python:
  - "2.7"

# command to install dependencies
script: python tests/__init__.py
branches:
  only:
    - master

sudo: false

cache:
  - apt
  - pip
addons:
  apt:
    packages:
      - python-scipy
      - python-numpy
      - python-pyside #probably not working
      - python-h5py
      - python-matplotlib
      - libqt4-dev


virtualenv:
  system_site_packages: true

install:
  - pip install PySide --no-index --find-links https://parkin.github.io/python-wheelhouse/;
  # Travis CI servers use virtualenvs, so we need to finish the install by the following
  - pip install .

script:
  - pip install pylint
  - pylint xicamlauncher xicam pipeline --errors-only
  - pip install coverage
  - coverage run tests.py

after_success:
  - pip install codecov --upgrade  # add coverage integration service
  #- codecov
  - bash <(curl -s https://codecov.io/bash)